export const getMessageStyle = ({ primaryColor, secondaryColor, textColor, theme, isAiAgentState, isSentFromUser }) => {
    const isAiAgentOnly = {
        innerContainer: {
            display: 'flex',
            flexDirection: 'column',
            gap: '0',
            padding: isSentFromUser ? '10px' : '5px 0',
            borderRadius: '8px',
            wordBreak: 'break-word',
        },
        userMessage: {
            background: 'rgba(242, 242, 242, 1)',
            color: 'rgb(51, 51, 51)',
            fontSize: '14px!important',
        },
        userTime: {
            textAlign: 'right',
            color: textColor ?? 'inherit',
        },
        agentMessage: {
            background: 'transparent',
            color: 'rgba(51, 51, 51, 1)!important',
            fontSize: '14px!important',
            LineHeight: '145%',
        },
        agentTime: {
            textAlign: 'left',
            color: ' rgba(130, 130, 130, 1)',
            fontSize: '12px!important',
        },
    };
    return {
        // common
        container: {
            maxWidth: '60%',
            marginTop: '5px',
            marginBottom: '5px',
            whiteSpace: 'pre-wrap',
            '@media (max-width: 768px)': {
                maxWidth: '100%',
            },
        },
        innerContainer: {
            display: 'flex',
            flexDirection: 'column',
            gap: '5px',
            padding: '10px',
            borderRadius: '8px',
            wordBreak: 'break-word',
        },
        userMessage: {
            background: primaryColor,
            color: textColor ?? 'inherit',
            fontSize: 'inherit',
        },
        userTime: {
            textAlign: 'right',
            color: textColor ?? 'inherit',
        },
        agentMessage: {
            background: secondaryColor ?? theme.color.darkGrey,
            color: textColor ?? 'inherit',
            fontSize: 'inherit',
            LineHeight: 'inherit',
        },
        agentTime: {
            textAlign: 'left',
            color: textColor ?? 'inherit',
            fontSize: 'inherit',
        },
        // video
        videoCallBanner: {
            display: 'flex',
            height: '100px',
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: '10px',
            marginBottom: '10px',
            borderRadius: '10px',
            cursor: 'pointer',
            overflow: 'hidden',
        },
        videoCallBannerIcon: {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            width: '70px',
            height: '100%',
            backgroundColor: '#1D4B91',
        },
        videoCallBannerMessage: {
            height: '100%',
            backgroundColor: '#39F',
            userSelect: 'none',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            gap: '10px',
            padding: '5px 10px',
            width: 'calc(100% - 70px)',
        },
        // file
        fileContainer: {
            transition: '0.3s ease-in-out',
        },
        fileImageInnerContainer: {
            width: '100%',
            height: 'fit-content',
            position: 'relative',
        },
        fileImage: {
            display: 'block',
            width: '100%',
            height: 'auto',
            objectFit: 'contain',
        },
        fileImageOverlay: {
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            height: '100%',
            width: '100%',
            borderRadius: '8px',
            opacity: 0,
            position: 'absolute',
            transition: '0.1s ease',
            cursor: 'pointer',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            color: 'white',
            '&:hover': {
                opacity: 1,
                backgroundColor: 'rgba(0, 0, 0, 0.5)',
            },
        },
        fileImageEnlarge: {
            maxWidth: '100%',
            width: '100%',
            transition: '0.3s ease-in-out',
        },
        // multiple choice
        multipleChoiceContainer: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-start',
            gap: '10px',
            marginTop: '10px',
        },
        multipleChoiceItem: {
            backgroundColor: theme.color.white,
            borderColor: primaryColor,
            color: primaryColor,
            textTransform: 'none',
            wordBreak: 'break-word',
            textAlign: 'start',
            '&:hover': {
                backgroundColor: primaryColor,
                color: textColor ?? 'inherit',
            },
            borderRadius: '8px',
            padding: '5px 10px 5px 10px',
        },
        subText: {
            whiteSpace: 'pre-line',
            color: 'rgba(130, 130, 130, 1)',
            borderLeft: '3px solid rgba(224, 224, 224, 1)',
            paddingLeft: '15px',
            marginLeft: '5px',
            lineHeight: '24px',
            fontWeight: 400,
            marginBottom: '20px',
            marginTop: '7px',
        },
        text: {
            whiteSpace: 'normal',
        },
        chartId: {
            display: 'flex',
            alignItems: 'center',
            padding: '2px 10px 1px 10px',
            background: 'rgba(251, 179, 81, 1)',
            color: 'rgba(255, 255, 255, 1)',
            width: 'fit-content',
            fontSize: '12px',
            borderRadius: '30px',
            fontWeight: 400,
        },
        counterValue: {
            padding: '0 10px',
            color: 'rgba(240, 160, 90, 1)',
            width: 'fit-content',
            border: '1px solid rgba(220, 140, 70, 1)',
            borderRadius: '0 10px 10px 0',
        },
        seeChartBtn: {
            backgroundColor: 'rgba(130, 130, 130, 1)',
            width: 'fit-content',
            padding: '3px 15px',
            display: 'flex',
            alignItems: 'center',
            color: '#f2f2f2',
            borderRadius: '20px',
            justifyContent: 'center',
            display: 'inline-block',
            '&:hover': {
                background: primaryColor,
            },
            '&:active': {
                background: primaryColor,
            },
            '&:focus-visible': {
                background: primaryColor,
            },
        },
        wrapper: {
            maxWidth: '100%',
            overflowX: 'auto',
        },
        typing: {
            color: 'grey',
            opacity: 0.65,
            fontStyle: 'italic',
            transition: 'opacity 0.2s',
        },
        table: {
            display: 'block',
            whiteSpace: 'nowrap',
            width: '100%',
            borderCollapse: 'collapse',
            fontSize: '0.9rem',
        },
        th: {
            background: '#fafafa',
            fontWeight: 600,
            textAlign: 'left',
            padding: '0.6rem 0.8rem',
            border: '1px solid #ddd',
        },
        td: {
            padding: '0.6rem 0.8rem',
            border: '1px solid #ddd',
        },
        trOdd: { background: '#fcfcfc' },
        ...(isAiAgentState ? isAiAgentOnly : {}),
    };
};
